### ISSUE TITLE
Error in browser console

### ISSUE THREAD

**Issue by Sa1ch** [paomedia/clearmin#3]
Hello!
I use jquery 3.1.1 and bootsrap 3
I constantly see an error:

> jQuery.Deferred exception: nav.size is not a function TypeError: nav.size is not a function
and

> Uncaught TypeError: nav.size is not a function

**Comment by paomedia** [comment]
Probably because jquery has removed the $('...').size() function
You should downgrade jquery or replace theses calls by the length property => $('...').length
